cart_page_url = "https://gardanetgame.azurewebsites.net/shoppingcart"
cart_develop_url = "https://gardanetgame-dev.azurewebsites.net/shoppingcart"
cart_section = "//h2[contains(text(), 'Your Shopping Cart')]"
minus_button = "(//button[contains(., '−')])[1]"
plus_button = "//button[contains(., '+')]"
checkout_button = "//a[contains(@href, '/checkout')]"
delete_button = "xpath=/html/body/div[3]/main/article/div/div[1]/div[1]/div/div[2]/div/div/button[3]"
product_card = "//div[contains(@class, 'card') and .//h5]"
quantity_input = "(//input[@class='form-control d-inline-block'])[1]"
cart_message = "xpath=//div[contains(@class, 'mud-alert')]"
empty_cart_text = "//h5[contains(text(), 'Your cart is empty.')]"
total_price_text = "//h5[strong[contains(., 'Total price')]]"
success_message = "xpath=//div[contains(@class, 'mud-alert-message') and contains(text(), 'har lagts till i varukorgen')]"
add_to_cart_button = "xpath=//button[.//span[contains(text(), 'Lägg i varukorgen')]]"